// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvLFySUDJy2bWfXlLbErhrHwAffuVTtMY',
    appId: '1:1058650819539:web:93e1f5b610f9fabfd7bd26',
    messagingSenderId: '1058650819539',
    projectId: 'zoom-clone-6f940',
    authDomain: 'zoom-clone-6f940.firebaseapp.com',
    storageBucket: 'zoom-clone-6f940.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-67e1b-_KkCtTb00i5oJDK3NBkKjjNQ',
    appId: '1:1058650819539:android:ed0482885759523ed7bd26',
    messagingSenderId: '1058650819539',
    projectId: 'zoom-clone-6f940',
    storageBucket: 'zoom-clone-6f940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4esxsEMx_X2sHz-6G6GLA1mjtSxgPT1Y',
    appId: '1:1058650819539:ios:3ee4bb34b2aff032d7bd26',
    messagingSenderId: '1058650819539',
    projectId: 'zoom-clone-6f940',
    storageBucket: 'zoom-clone-6f940.firebasestorage.app',
    iosClientId: '1058650819539-186qvhib85fsuvoeev7crbmbii3pgcnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4esxsEMx_X2sHz-6G6GLA1mjtSxgPT1Y',
    appId: '1:1058650819539:ios:3ee4bb34b2aff032d7bd26',
    messagingSenderId: '1058650819539',
    projectId: 'zoom-clone-6f940',
    storageBucket: 'zoom-clone-6f940.firebasestorage.app',
    iosClientId: '1058650819539-186qvhib85fsuvoeev7crbmbii3pgcnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvLFySUDJy2bWfXlLbErhrHwAffuVTtMY',
    appId: '1:1058650819539:web:5aa2d86f99029618d7bd26',
    messagingSenderId: '1058650819539',
    projectId: 'zoom-clone-6f940',
    authDomain: 'zoom-clone-6f940.firebaseapp.com',
    storageBucket: 'zoom-clone-6f940.firebasestorage.app',
  );
}
